#!/usr/bin/env sh

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# global settings
yabai -m config mouse_follows_focus on
yabai -m config focus_follows_mouse off
yabai -m config window_placement second_child
yabai -m config window_zoom_persist off
yabai -m config window_shadow float
yabai -m config window_opacity on
yabai -m config window_opacity_duration 0.1
yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 0.95
yabai -m config window_animation_duration 0.2
yabai -m config window_animation_frame_rate 120
yabai -m config insert_feedback_color 0xff9dd274
yabai -m config split_ratio 0.50
yabai -m config auto_balance off
yabai -m config top_padding 10
yabai -m config bottom_padding 10
yabai -m config left_padding 10
yabai -m config right_padding 10
yabai -m config window_gap 13
yabai -m config layout bsp
yabai -m config mouse_modifier alt
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize
yabai -m config mouse_drop_action swap

borders active_color=0xff005991 inactive_color=0xff48494f width=3.0 &
yabai -m rule --add app="^(LuLu|Calculator|Software Update|AppCleaner|Font Book|Dictionary|VLC|System Preferences|System Settings|Photo Booth|Archive Utility|App Store|Steam|Alfred|Activity Monitor|Alfred Preferences|Notion|Mousecape|Latest|Calendar|Clock|Telegram|TextEdit|Shottr|Karabiner-Elements|Notes|DaisyDisk)$" manage=off
yabai -m rule --add app="^Mac Mouse Fix$" title="Mac Mouse Fix" manage=off
yabai -m rule --add app="^(Preview|Music|Spotify|Spark|Stats|Finder)$" manage=off
yabai -m rule --add app="^Telegram$" layer=normal manage=off

echo "yabai configuration loaded.."
